### ISSUE TITLE
Autocomplete-snippets not working for some/all scopes? 2nd

### ISSUE THREAD

**Issue by Heiko-san** [atom/autocomplete-snippets#84] opened 2017-05-01 17:31 UTC
## Description

related to #83 ...
I can reproduce the issue using latest ubuntu with the deb package on https://atom.io/ 

PS: 
Is this really what atom is all about?
I thought an editor which is highly modular would be a good idea...
but what it seems it is all about is a piece of software without any community...
At least if you are a newbe, it seems atom is a "Everyone works for himself" project...
I created issues at X different places , everyone just points you in a different location and in the end your issue is closed with "sorry not supported" ...
I really think the basic idea of atom is great and would like to learn nodejs just to provide some extentions for atom ... but it seems this is actually a waste of time ...
Sorry if this sounds hard , but 2 weeks of creating issues about this and no one did even try to help me with this. This is really frustrating. :(
Especially as I don't say that it is a bug per se ... I would bet that I'm just missing a little thing that is obvious to someone using atom for years.

**Comment by lee-dohm** [comment] 2017-05-02 18:07
Hello @Heiko-san, thanks for reaching out.

I'm not sure what you mean by "I created issues at X different places , everyone just points you in a different location" and "2 weeks of creating issues about this". I only see [these two issues opened by you](https://github.com/search?utf8=%E2%9C%93&q=user%3Aatom+is%3Aissue+author%3AHeiko-san&type=) in the entire Atom org, the earliest of which was opened a day ago as of this writing. Is there something that I'm missing?

We definitely do our best to help people. Yes, there are limitations to how far we go in doing that. One of those limitations is [supporting the builds of Atom that other people or groups produce](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md) that have been shown in the past to cause an inordinate amount of support load. This excess support cost is specifically because of the changes that these third parties make to Atom before distributing it. It was preventing us from helping people that use official versions of Atom. So we had to make a choice and we feel it is completely reasonable to not support something that we didn't create.

Thanks for letting us know that you can reproduce this in a supported version of Atom. Leaving aside the Salt stuff (since it isn't applicable in Safe Mode), I can reproduce the problem you're describing using Atom v1.16.0 on Mac OS X 10.12.4 using the following steps:

1. Launch Atom
1. Replace the contents of `snippets.cson` with the text shown below
1. Open a new file using <kbd>Cmd+N</kbd>
1. Change the grammar to JavaScript by clicking the grammar selector and selecting `JavaScript` from the list of grammars
1. Type `foo`
1. Observe the full autocomplete-snippets interface shown
1. Open a new file using <kbd>Cmd+N</kbd>
1. Change the grammar to YAML by clicking the grammar selector and selecting `YAML` from the list of grammars
1. Type `foo`

**Expected:** Get the full autocomplete-snippets interface

<img width="262" alt="screen shot 2017-05-02 at 11 01 45 am" src="https://cloud.githubusercontent.com/assets/1038121/25631997/f554bfa8-2f26-11e7-9bd2-f721c9903f07.png">

**Actual:** Looks like we get only the default autocomplete provider

<img width="214" alt="screen shot 2017-05-02 at 11 01 32 am" src="https://cloud.githubusercontent.com/assets/1038121/25632008/fd17b9de-2f26-11e7-80b6-92acde1d0cde.png">

### snippets.cson

```coffee
'.source.yaml':
  'test entry':
    'prefix': 'foo'
    'description': 'This is a foobar snippet for yaml.'
    'descriptionMoreURL': 'https://docs.saltstack.com/en/latest/ref/states/requisites.html'
    'body': "foobarbaz"
'.source.js':
  'test entry':
    'prefix': 'foo'
    'description': 'This is a foobar snippet for js.'
    'descriptionMoreURL': 'https://docs.saltstack.com/en/latest/ref/states/requisites.html'
    'body': "foobarbaz"
```

**Comment by Heiko-san** [comment] 2017-05-02 18:24
Hi, sorry maybe I was a little too frustrated by trying to find the right place for this issue , it is really hard to tell where to address issues with all that package distributions.

With default autocompleter you mean the one showing words already used in the document so far?
Since I can confirm I'm getting this one. If the document is completely empty no autocompletion is shown at all.

First I thought I would have to write a provider specific for salt (or yaml if you want to leave salt out), this was when I read about the autocomplete-snippets provider.
I thought maybe it doesn't implement descriptions etc. (I guess I got confused with the default provider at this point).
After having a look into the code I first considered the posibilty that it may be a bug.
May this simply be an issue with provider priority?

**Comment by Heiko-san** [comment] 2017-05-02 18:47
I guess you are right , disabling the built-in provider doesn't change anything.

**Comment by Ilias48rus** [comment] 2017-07-17 14:37
lee-dohm
im having the issue right now its very sad because i using snippets alot, is any way to fix it ? | When it will be fixed ?

**Comment by Ilias48rus** [comment] 2017-07-26 00:13
and i do have the snippets in "available" package's tab.
Heey, anyone here ?

**Comment by Ilias48rus** [comment] 2017-07-26 01:13
Changed few package's settings and the problem fixed, changed them back, but the problem didn't reproduced, also got a question is it normal behaviour of the package:
![untitled3](https://user-images.githubusercontent.com/13949704/28600132-b80785de-71b8-11e7-9a61-b08a1f13e135.png)
screenshots?

**Comment by happycollision** [comment] 2017-11-28 03:23
I am also experiencing this issue with YAML files. For anyone with this problem, the workaround I am using is to also add `.text.plain` to the snippet class and just using the grammar picker in the lower right to temporarily change the file to Plain Text while I am editing it.

YAML is pretty nice to look at even without highlighting, so it's a decent stop-gap while this issue is being addressed.

**Closed** 2018-01-18 17:48 UTC
Labels: bug, triaged
