### ISSUE TITLE
\n string completion

### ISSUE THREAD

**Issue by bobhob314** [atom/autocomplete-snippets#74] opened 2016-07-15 18:59 UTC
When you type a \n in " quotation marks and then try to close the string, an extra " quotation mark shows up.

**Comment by lee-dohm** [comment] 2016-07-15 19:11
This is a duplicate of https://github.com/atom/bracket-matcher/issues/80. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-15 19:11 UTC
