### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by chermed** [atom/autocomplete-snippets#54] opened 2015-05-28 11:44 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.202.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autocomplete-snippets](https://github.com/atom/autocomplete-snippets) package, v1.6.3

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-snippets/lib/snippets-provider.js:73

TypeError: Cannot read property 'toLowerCase' of undefined
  at firstCharsEqual (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-snippets/lib/snippets-provider.js:73:19)
  at SnippetsProvider.module.exports.SnippetsProvider.findSuggestionsForPrefix (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-snippets/lib/snippets-provider.js:41:26)
  at SnippetsProvider.module.exports.SnippetsProvider.getSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-snippets/lib/snippets-provider.js:30:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```

### Commands

```
     -7:05.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:04.1.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:15.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:38.3.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  2x -5:37.6.0 core:save (atom-text-editor.editor.is-focused)
  5x -1:18.7.0 core:undo (atom-text-editor.editor.is-focused)
     -1:16.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:13.8.0 git-plus:menu (atom-text-editor.editor.is-focused)
  3x -1:12.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:11.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:07.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:05.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:44 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "followSymlinks": true,
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "*.pyc",
      "*.pyo",
      ".gitignore",
      "*~"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.8
autocomplete-paths, v1.0.2
git-plus, v5.0.1
git-projects, v1.14.1
linter, v0.12.6
linter-flake8, v1.4.2
minimap, v4.9.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0

# Dev
No dev packages
```

**Comment by benogle** [comment] 2015-05-28 17:02
Do you remember what you were doing when this happened? Do you remember what you were typing? Looks like it happened 3 seconds after typing a newline. Was it triggered on the newline? Any steps you can give me so I can reproduce?

**Comment by chermed** [comment] 2015-05-29 11:47
Just in xml file,
I have some snippet of XML, when I type a letter  the error shown, so if I type  a word of 5 letter I get 5 errors
I think that the problem come when the plugin try to load the snippet
In the same editor, the snippet of python work well,
I can send you a video if you want

(I update all packages everyday)

**Comment by benogle** [comment] 2015-05-29 17:22
Can you try `atom --safe`? If it still errors, can you rename your `~/.atom` folder and try again?

My gut is that one of the package has a bs snippet.

**Comment by benogle** [comment] 2015-05-29 17:26
Fixed in https://github.com/atom/autocomplete-snippets/commit/1e36979bc01a7bee941075043d42b75e68fb4922

**Closed by benogle** 2015-05-29 17:26 UTC
